# Generated by Django 2.1.15 on 2020-12-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
    ]
